# DSM Storage Node Configuration for Local Testing

[api]
bind_address = "127.0.0.1"
port = 8080
enable_cors = true
enable_rate_limits = false
max_body_size = 10485760  # 10MB

[node]
id = "node_1"
name = "Local Storage Node 1"
region = "local"
operator = "developer"
version = "1.0.0"
description = "Local development storage node"
public_key = "test_public_key_1"
endpoint = "http://127.0.0.1:8080"

[storage]
engine = "sqlite"
capacity = 107374182400  # 100GB
data_dir = "./data"
database_path = "./data/dsm_storage.db"
assignment_strategy = "DeterministicHashing"
replication_strategy = "FixedReplicas"
replica_count = 1
min_regions = 1
default_ttl = 0
enable_pruning = false
pruning_interval = 3600

[network]
listen_addr = "127.0.0.1"
public_endpoint = "http://127.0.0.1:8080"
port = 8080
max_connections = 100
connection_timeout = 30
bootstrap_nodes = []
enable_discovery = true
discovery_interval = 60
max_peers = 50
